version: "3"

services:
  mongo:
    image: "mongo:6"
    restart: "always"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - "db-data:/var/lib/mongo"
    networks:
      - "localnetwork"
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: "always"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: "mongo"
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
    networks:
      - "localnetwork"
networks:
  localnetwork:

volumes:
  db-data:
